[global]
bdev_enable_discard = true
bdev_async_discard = true
osd_class_update_on_start = false
bluestore_prefer_deferred_size = 0
bluestore_deferred_batch_ops = 16
bluestore_deferred_batch_ops_per_txn = 32
bluestore_min_alloc_size = 4096
bluestore_compression_algorithm = none
bdev_flock_retry = 3

