apiVersion: v1
kind: Secret
metadata:
    name: truenas-capacity-secret
stringData:
    #ENC[AES256_GCM,data:JOWvtANCp2byRW4R0Uwbum3Gs8mGEPG5/bGvlMzrzqbX0XDrvkgGlAM6XoKFALznpgst3Ma6u0IVTodEKEMgT/KijWtXOkGZUZ2iGy0=,iv:b+Z5PJRFPG6+qZPiFIuWtgywXNkO8FMNNb9ECrhNzqc=,tag:XmNTLGJoWllzJXvDh9om3Q==,type:comment]
    #ENC[AES256_GCM,data:D0pAlcPyI3tK9RMRmDUgxJa+GPkiZTEwnIZoPcx68AcO9r6bQwTXLUJgld4YWQwSrYMBQnLRUHkb10wAeuP0qD/K2hgOKtuiGw0=,iv:QG8GGCzbUUU/Z51+1Yx5T70Jx/H86KmCgOCc8hucIk0=,tag:je1d/DyegCEuxOK0VqBxRw==,type:comment]
    #ENC[AES256_GCM,data:CZlYm08BOEBjyDIymwprW4mN6HSWu3RsTEN6EhttAUHmzOWVzw6RhdzTsgfm9pQR807loGT3JRzASEqmPcn2sLCZ0vGJ/gY99w==,iv:WBTwyuMTQVnKFbGfly3xEtCx7Efvwf2o5xBGY4CTGPE=,tag:cwVUOTeYV7b2TLzwgF1Xew==,type:comment]
    #ENC[AES256_GCM,data:KaLivKe8j4zTt30mlDdVzBqUONZlsLFPrJJwNNY29mlHoZlD43Soo258hTLUi/vqcvvRqgeaVhC5uFqY2ngoNr4=,iv:vgyyuwTTiGcL2Xw4DTV6RSl4lbmW18Xxj9LrWPl9DRk=,tag:D8uJYnEvCw95JzHPK5211Q==,type:comment]
    TRUENAS_API_KEY: ENC[AES256_GCM,data:GDJgXRkP+Ll6r7Wz3E3yYsjywAFAQnBoZxVERImkV3GrpDm3a7ZyuVSdoPm0dX4QSP08XFNuoe2/j1u3eGmDh3WL,iv:3128JOQQel5CNm8TlfCHBAgtQFYZbF5Jcw0g0lej/QY=,tag:G0Uz4O63o4bb0gSCfzwlYA==,type:str]
sops:
    age:
        - recipient: age1s3dkl4qn66zsj38zl4nkjdw8c6j4d9v8ddd9vwajcfjrz04s2fgsgg3lxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNUXZMR2ozVXdvbEFXcmJU
            bUk2T0JrektGdzBuSG10RlUwVWhCS0dMNDJJCkxBRndjQURWSTFSL3Z6eFJBT2Fw
            L0lxZXdtbHN3blIrNFpTaGhPOEt6QU0KLS0tIFpqMWd2ZHdWb3RMNTJiNE55SmlW
            UmUxL3IzMHNkcDBCSlR1RndPVEJoMU0KTJs2oE0kW8MpLDjgsGjlSf+qR8Pf/bLA
            cWUn4CkHamsCcSMzPpCJ/7plHDLOtO/O723qJZR9OyoJmcbfnbCmdA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-29T08:59:34Z"
    mac: ENC[AES256_GCM,data:MjfppKc00BOUKjU9ZLCTo3dowb6it4u3mYlghPlNzG2avmKrXQca8WKj9mP05JWJQQXgPW6suEItYYRWXD0ibkFCDmnKjsHe0oTGJxCYxVBe17yLhTRArBeYgHUDnmAyL4kLh8fpLrev1Fq1XCce1dU6qgG/wkjGkA8XTeon7/w=,iv:VzhXjNePRZdQ79cqFjmRakO3e/60DiCKd4jqN6HIZSE=,tag:kcGHV6KJ8J9yseWrg3VS3w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
