---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./externalsecret.yaml
  - ./helmrelease.yaml
components:
  - ../../../../components/priority/priority-08
configMapGenerator:
  - name: autobrr-loki-rules
    files:
      - ./resources/lokirule.yaml
    options:
      labels:
        loki_rule: "true"
      annotations:
        # Loki's rules sidecar files this under the single-tenant ("fake") rule directory.
        k8s-sidecar-target-directory: /rules/fake
generatorOptions:
  disableNameSuffixHash: true
