---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: speediance-influx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: speediance-influx-secret
    template:
      engineVersion: v2
      data:
        config.toml: |
          [[users]]
          name = "Gavin"
          email = "{{ .SPEEDIANCE_EMAIL }}"
          password = "{{ .SPEEDIANCE_PASSWORD }}"
          region = "Global"

          [[users]]
          name = "Serina"
          email = "{{ .SPEEDIANCE_EMAIL_2 }}"
          password = "{{ .SPEEDIANCE_PASSWORD_2 }}"
          region = "Global"

          [influx]
          url = "http://influxdb.vitals.svc.cluster.local:8086"
          bucket = "health"
          token = "{{ .INFLUXDB_ADMIN_TOKEN }}"
          org = "vitals"

          [main]
          log_level = "INFO"
          loop_minutes = 60
          write_sets = true
          write_muscles = true
          write_1rm = true
  dataFrom:
    - extract:
        key: speediance-influx
    - extract:
        key: influxdb
