CREATE DATABASE "immich";
\c immich
BEGIN;
ALTER DATABASE "immich" OWNER TO "immich";
CREATE EXTENSION IF NOT EXISTS vchord CASCADE;
CREATE EXTENSION vector CASCADE;
CREATE EXTENSION earthdistance CASCADE;
COMMIT;