---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
# Single `lighthouse` 1Password item → one k8s Secret. Keys:
#   client-id / client-secret    → Envoy SecurityPolicy OIDC (bentopdf convention)
#   LIGHTHOUSE_DR_TOKEN          → licence-gate proxy (brand service-account bearer)
#   LIGHTHOUSE_WORKER_TOKEN      → model-serve sidecar (worker fetch auth)
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: lighthouse
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: lighthouse-secret
    template:
      engineVersion: v2
      data:
        client-id: "{{ .LIGHTHOUSE_OIDC_CLIENT_ID }}"
        client-secret: "{{ .LIGHTHOUSE_OIDC_CLIENT_SECRET }}"
        LIGHTHOUSE_DR_TOKEN: "{{ .LIGHTHOUSE_DR_TOKEN }}"
        LIGHTHOUSE_WORKER_TOKEN: "{{ .LIGHTHOUSE_WORKER_TOKEN }}"
  dataFrom:
    - extract:
        key: lighthouse
