---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/gateway.envoyproxy.io/securitypolicy_v1alpha1.json
# OIDC at the edge (Pocket-ID). forwardAccessToken puts the verified id_token on
# `Authorization: Bearer` for the licence-gate proxy, which DECODES (not verifies)
# it — safe only because this SecurityPolicy verifies upstream AND the NetworkPolicy
# makes the proxy reachable only via Envoy. The `groups` scope carries the role
# claims (family-adult / family-minor / mature-content) the proxy reads.
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: SecurityPolicy
metadata:
  name: lighthouse-oidc
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: lighthouse
  oidc:
    provider:
      backendRefs:
        - group: gateway.envoyproxy.io
          kind: Backend
          name: lighthouse-oidc-provider
          port: 1411
      issuer: "https://id.${SECRET_DOMAIN}"
      authorizationEndpoint: "https://id.${SECRET_DOMAIN}/authorize"
      tokenEndpoint: "https://id.${SECRET_DOMAIN}/api/oidc/token"
    clientIDRef:
      name: lighthouse-secret
    clientSecret:
      name: lighthouse-secret
    redirectURL: "https://lighthouse.nerdz.cloud/oauth2/callback"
    logoutPath: "/logout"
    forwardAccessToken: true
    scopes: ["openid", "profile", "email", "groups"]
