---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vitals

components:
  - ../../components/common

resources:
  - ./influxdb/ks.yaml
  - ./telegraf/ks.yaml
  - ./apple-health-ingester/ks.yaml
  - ./resmed-influx/ks.yaml
  - ./sleeptracker-influx/ks.yaml
  - ./speediance-influx/ks.yaml
  - ./sparkyfitness/ks.yaml
