---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: zot
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: zot-auth
    template:
      engineVersion: v2
      data:
        # bcrypt htpasswd line(s). Generate with: htpasswd -nbB admin '<password>'
        htpasswd: "{{ .ZOT_HTPASSWD }}"
  dataFrom:
    - extract:
        key: zot
