---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resmed-influx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: resmed-influx-secret
    template:
      engineVersion: v2
      data:
        MYAIR_INFLUX_RESMED_LOGIN: "{{ .RESMED_LOGIN }}"
        MYAIR_INFLUX_RESMED_PASSWORD: "{{ .RESMED_PASSWORD }}"
        MYAIR_INFLUX_INFLUX_TOKEN: "{{ .INFLUXDB_ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: resmed-influx
    - extract:
        key: influxdb
