---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: resmed-influx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: resmed-influx-secret
    template:
      engineVersion: v2
      data:
        config.toml: |
          [resmed]
          login = "{{ .RESMED_LOGIN }}"
          password = "{{ .RESMED_PASSWORD }}"
          region = "NA"
          max_days = 365

          [influx]
          url = "http://influxdb.vitals.svc.cluster.local:8086"
          bucket = "health"
          measurement = "cpap"
          token = "{{ .INFLUXDB_ADMIN_TOKEN }}"
          org = "vitals"

          [main]
          logverbosity = "INFO"
          loop_minutes = 60
  dataFrom:
    - extract:
        key: resmed-influx
    - extract:
        key: influxdb
