---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: p4k-scanner-output
  namespace: home
  labels:
    app.kubernetes.io/name: p4k-scanner
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ceph-block
  resources:
    requests:
      storage: 10Gi
