---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: filebrowser
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: filebrowser-secret
    template:
      engineVersion: v2
      data:
        config.yaml: |
          server:
            port: 80
            root: /media
          auth:
            methods:
              password:
                enabled: false
              oidc:
                enabled: true
                clientId: "{{ .FILEBROWSER_OIDC_CLIENT_ID }}"
                clientSecret: "{{ .FILEBROWSER_OIDC_CLIENT_SECRET }}"
                issuerUrl: https://id.${SECRET_DOMAIN}
                scopes: email openid profile groups
                userIdentifier: preferred_username
                createUser: true
  dataFrom:
    - extract:
        key: filebrowser
