---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sleeptracker-influx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: sleeptracker-influx-secret
    template:
      engineVersion: v2
      data:
        config.toml: |
          [sleeptracker]
          email = "{{ .SLEEPTRACKER_EMAIL }}"
          password = "{{ .SLEEPTRACKER_PASSWORD }}"
          max_days = 365

          [influx]
          url = "http://influxdb.vitals.svc.cluster.local:8086"
          bucket = "health"
          token = "{{ .INFLUXDB_ADMIN_TOKEN }}"
          org = "vitals"

          [main]
          log_level = "INFO"
          loop_minutes = 60
          write_cardio = true
          write_stages = true
          write_events = true
  dataFrom:
    - extract:
        key: sleeptracker-influx
    - extract:
        key: influxdb
