---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apple-health-ingester
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: apple-health-ingester-secret
    template:
      engineVersion: v2
      data:
        INFLUXDB_TOKEN: "{{ .INFLUXDB_TOKEN }}"
        APPLE_INGESTOR_AUTH_TOKEN: "{{ .APPLE_INGESTOR_AUTH_TOKEN }}"
  dataFrom:
    - extract:
        key: apple-health-ingester
