---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s-labs/helm-charts/common-4.4.0/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apple-health-ingester
spec:
  interval: 30m
  chart:
    spec:
      chart: app-template
      version: 4.4.0
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    controllers:
      apple-health-ingester:
        annotations:
          reloader.stakater.com/auto: "true"
        containers:
          app:
            image:
              repository: docker.io/irvinlim/apple-health-ingester
              tag: v0.5.0@sha256:43124d11fb4368f4d977d2b5a8ef625350b4b3b3e06f3acc093dd6330ac4c025
            args:
              - --backend.influxdb
              - --influxdb.serverURL=http://influxdb-app.vitals.svc.cluster.local:8086
              - --influxdb.authToken=$(INFLUXDB_TOKEN)
              - --influxdb.orgName=vitals
              - --influxdb.metricsBucketName=health
              - --influxdb.workoutsBucketName=health
              - --http.authToken=$(APPLE_INGESTOR_AUTH_TOKEN)
            envFrom:
              - secretRef:
                  name: apple-health-ingester-secret
            probes:
              liveness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: &port 8080
                  initialDelaySeconds: 5
                  periodSeconds: 30
              readiness:
                enabled: true
                custom: true
                spec:
                  httpGet:
                    path: /
                    port: *port
                  initialDelaySeconds: 5
                  periodSeconds: 10
            securityContext:
              allowPrivilegeEscalation: false
              readOnlyRootFilesystem: true
              capabilities: { drop: ["ALL"] }
            resources:
              requests:
                cpu: 10m
                memory: 64Mi
              limits:
                memory: 256Mi
    defaultPodOptions:
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534
        runAsGroup: 65534
        fsGroup: 65534
        seccompProfile: { type: RuntimeDefault }
    service:
      app:
        controller: apple-health-ingester
        ports:
          http:
            port: *port
    route:
      app:
        annotations:
          external-dns.alpha.kubernetes.io/target: external.${SECRET_DOMAIN}
        hostnames:
          - health-ingest.${SECRET_DOMAIN}
        parentRefs:
          - name: external
            namespace: network
            sectionName: https
    persistence:
      tmp:
        type: emptyDir
        globalMounts:
          - path: /tmp
