---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: &name local-ai
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: local-ai-secret
    template:
      engineVersion: v2
      data:
        TOKEN: "{{ .LOCALAI_P2P_TOKEN }}"
  dataFrom:
    - extract:
        key: local-ai
