---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: influxdb
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: influxdb-secret
    template:
      engineVersion: v2
      data:
        DOCKER_INFLUXDB_INIT_USERNAME: "{{ .INFLUXDB_ADMIN_USERNAME }}"
        DOCKER_INFLUXDB_INIT_PASSWORD: "{{ .INFLUXDB_ADMIN_PASSWORD }}"
        DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: "{{ .INFLUXDB_ADMIN_TOKEN }}"
  dataFrom:
    - extract:
        key: influxdb
