{
 "title": "Qdrant Vector DB Dashboard",
 "description": "An overview of qdrant",
 "tags": [
  "observability",
  "database",
  "vector",
  "cortex",
  "qdrant"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Operator Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Deployment Status Over Time",
   "type": "state-timeline",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "kube_deployment_status_replicas_available{deployment=\"qdrant\"}",
     "legendFormat": "{{namespace}}"
    }
   ]
  },
  {
   "title": "Operator Versions",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 1 },
   "targets": [
    {
     "expr": "group(kube_pod_container_info{container=\"app\", pod=~\"qdrant.*\"}) by(namespace,image)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Qdrant Version Info",
   "type": "table",
   "description": "Version information of Qdrant instances",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 7 },
   "targets": [
    { "expr": "qdrant:app_info", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "description": "CPU usage by Qdrant operator instances across all managed cloud regions",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"cortex\", pod=~\"qdrant.*\", container=\"app\"}[5m]) * 100",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "description": "Memory usage by Qdrant operator instances across all managed cloud regions",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "container_memory_usage_bytes{namespace=\"cortex\", pod=~\"qdrant.*\", container=\"app\"}",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Total Collections",
   "type": "timeseries",
   "description": "Total number of collections across Qdrant instances",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "qdrant:collections_total", "legendFormat": "{{namespace}}/{{pod}}" }
   ]
  },
  {
   "title": "Total Vectors",
   "type": "timeseries",
   "description": "Total vectors across all collections in Qdrant instances",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "qdrant:collections_vector_total",
     "legendFormat": "{{namespace}}/{{pod}}"
    }
   ]
  },
  {
   "title": "Active Memory",
   "type": "timeseries",
   "description": "Memory actively used by Qdrant instances",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "qdrant:memory_active_bytes", "legendFormat": "{{namespace}}/{{pod}}" }
   ]
  },
  {
   "title": "Allocated Memory",
   "type": "timeseries",
   "description": "Memory allocated by Qdrant instances",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    { "expr": "qdrant:memory_allocated_bytes", "legendFormat": "{{namespace}}/{{pod}}" }
   ]
  }
 ]
}