{
 "title": "Cortex - Resource Overview",
 "tags": [
  "cortex",
  "observability",
  "nodes"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "CPU Usage - All Cortex associated pods (millicores)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Millicores" } },
   "targets": [
    {
     "expr": "(\r\n  sum(\r\n    rate(container_cpu_usage_seconds_total{namespace=\"cortex\"}[5m])\r\n  ) by (node)\r\n)\r\n+\r\n(\r\n  sum(\r\n    rate(container_cpu_usage_seconds_total{namespace=\"home\", pod=~\"searxng.*\"}[5m])\r\n  ) by (node)\r\n)\r\n* 1000\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory Usage per Node (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (instance) (\r\n    container_memory_usage_bytes{namespace=\"cortex\"}\r\n  )\r\n  +\r\n  sum by (instance) (\r\n    container_memory_usage_bytes{namespace=\"home\", pod=~\"searxng.*\"}\r\n  )\r\n) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Receive per Node (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (node) (\r\n    rate(container_network_receive_bytes_total{namespace=\"cortex\"}[5m])\r\n  )\r\n  +\r\n  sum by (node) (\r\n    rate(container_network_receive_bytes_total{namespace=\"home\", pod=~\"searxng.*\"}[5m])\r\n  )\r\n) * 8 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network Transmit per Node (Mbps)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "Mbps" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (node) (\r\n    rate(container_network_transmit_bytes_total{namespace=\"cortex\"}[5m])\r\n  )\r\n  +\r\n  sum by (node) (\r\n    rate(container_network_transmit_bytes_total{namespace=\"home\", pod=~\"searxng.*\"}[5m])\r\n  )\r\n) * 8 / 1024 / 1024",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Usage per Node (GB)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "decgbytes" } },
   "targets": [
    {
     "expr": "(\r\n  sum by (node) (\r\n    kubelet_volume_stats_used_bytes{namespace=\"cortex\"}\r\n  )\r\n  or vector(0)\r\n  +\r\n  sum by (node) (\r\n    kubelet_volume_stats_used_bytes{namespace=\"home\", persistentvolumeclaim=~\"searxng.*\"}\r\n  )\r\n  or vector(0)\r\n) / 1024 / 1024 / 1024\r\n",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}