{
 "title": "Cortex - SearXNG Metrics",
 "tags": [
  "searxng",
  "observability",
  "search"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "SearXNG - Up",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"searxng\", namespace=\"home\"} >0"
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 8, "x": 4, "y": 0 },
   "targets": [
    {
     "expr": "rate(searxng_engines_request_count_total[5m])",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "HTTP Response Time per Engine (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "searxng_engines_response_time_http_seconds",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Total Results Returned",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(searxng_engines_result_count_total[5m])",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Total Response Time per Engine (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "searxng_engines_response_time_total_seconds",
     "legendFormat": "{{engine_name}}"
    }
   ]
  },
  {
   "title": "Scrape Duration (Seconds)",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{job=\"searxng\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Scrape Samples Scraped",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "targets": [
    {
     "expr": "scrape_samples_scraped{job=\"searxng\"}",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}