{
 "title": "Radarr",
 "description": "This is a dashboard for Radarr v3 (based off https://grafana.com/grafana/dashboards/12896 from madchr1st ). \n\nYou will need to install exportarr (https://github.com/onedr0p/exportarr) in order to use this dashboard.\n\nYou will also need the following plugin for the more advanced panels: https://grafana.com/grafana/plugins/gapit-htmlgraphics-panel/",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "endpoint",
    "query": {
     "query": "query_result(exportarr_app_info{job=\"exportarr-radarr\"})"
    }
   }
  ]
 },
 "panels": [
  { "title": "${endpoint}", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "endpoint" },
  {
   "type": "gapit-htmlgraphics-panel",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "options": {
    "reduceOptions": {
     "calcs": [
      "lastNotNull",
      "last",
      "firstNotNull",
      "first",
      "min",
      "max",
      "mean",
      "sum",
      "count",
      "range",
      "delta",
      "step",
      "diff",
      "logmin",
      "allIsZero",
      "allIsNull",
      "diffperc"
     ]
    }
   },
   "targets": [
    {}
   ]
  },
  {
   "title": "Downloads",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (radarr_queue_total{endpoint=\"$endpoint\"})\r\nOR on (endpoint)\r\n(0 * exportarr_app_info{endpoint=\"$endpoint\"})",
     "legendFormat": "Queued"
    },
    {
     "expr": "radarr_history_total{endpoint=\"$endpoint\"}",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Movies",
   "type": "stat",
   "gridPos": { "h": 6, "w": 4, "x": 4, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint) (radarr_movie_missing_total{endpoint=\"$endpoint\"})",
     "legendFormat": "Missing"
    },
    {
     "expr": "sum by (endpoint) (radarr_movie_monitored_total{endpoint=\"$endpoint\"})",
     "legendFormat": "Monitored"
    },
    {
     "expr": "sum by (endpoint) (radarr_movie_total{endpoint=\"$endpoint\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Codecs",
   "type": "table",
   "gridPos": { "h": 6, "w": 4, "x": 8, "y": 4 },
   "targets": [
    {
     "expr": "sum by (codec, order) (\r\n  # h265\r\n  label_replace(\r\n    label_replace(\r\n      radarr_movie_tag_total{endpoint=\"$endpoint\", tag=~\".*codec.*h.?265.*\"},\r\n      \"codec\", \"h265\", \"tag\", \".*\"\r\n    ),\r\n    \"order\", \"1\", \"tag\", \".*\"\r\n  )\r\nor\r\n  # h264\r\n  label_replace(\r\n    label_replace(\r\n      radarr_movie_tag_total{endpoint=\"$endpoint\", tag=~\".*codec.*h.?264.*\"},\r\n      \"codec\", \"h264\", \"tag\", \".*\"\r\n    ),\r\n    \"order\", \"2\", \"tag\", \".*\"\r\n  )\r\nor\r\n  # vc1\r\n  label_replace(\r\n    label_replace(\r\n      radarr_movie_tag_total{endpoint=\"$endpoint\", tag=~\".*codec.*vc1.*\"},\r\n      \"codec\", \"vc1\", \"tag\", \".*\"\r\n    ),\r\n    \"order\", \"3\", \"tag\", \".*\"\r\n  )\r\nor\r\n  # everything else (still codec-tagged)\r\n  label_replace(\r\n    label_replace(\r\n      radarr_movie_tag_total{endpoint=\"$endpoint\", tag=~\".*codec.*\"}\r\n        unless radarr_movie_tag_total{endpoint=\"$endpoint\", tag=~\".*codec.*(h.?26[45]|vc1).*\"},\r\n      \"codec\", \"$1\", \"tag\", \".*codec[-= ]?([^, ]+).*\"\r\n    ),\r\n    \"order\", \"4\", \"tag\", \".*\"\r\n  )\r\n)\r\n",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Episode Quality: ${endpoint}",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(\r\n  sum by (quality) (\r\n    radarr_movie_quality_total{endpoint=\"$endpoint\"}\r\n  )\r\n)\r\n",
     "legendFormat": "{{ quality }}"
    }
   ]
  },
  {
   "title": "Status: ${endpoint}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 10 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max by (deployment) (\r\n  kube_deployment_status_condition{\r\n    namespace=\"downloads\",\r\n    deployment=\"$endpoint\",\r\n    condition=\"Available\",\r\n    status=\"true\"\r\n  }\r\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Uptime: ${endpoint}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - kube_deployment_created{deployment=\"$endpoint\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Storage Used: ${endpoint}",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (endpoint)(radarr_movie_filesize_total{endpoint=\"$endpoint\"})"
    }
   ]
  }
 ]
}