---
apiVersion: v1
kind: ConfigMap
metadata:
  name: anytype-cli-network
data:
  network.yml: |
    networkId: N7mRCiFwb2t3s1xQRRFPp1prT7ySqNa64yMXRfSm3XmwbL2k
    nodes:
      - peerId: 12D3KooWRuu1vzveWd6Jd3aiabdGatBNqFkBZVLzLM7kQfntHzeh
        addresses:
          - quic://10.99.8.214:33020
          - 10.99.8.214:33010
        types:
          - coordinator
          - consensus
          - tree
          - file
