---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: telegraf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: telegraf-secret
    template:
      engineVersion: v2
      data:
        INFLUX_TOKEN: "{{ .INFLUXDB_ADMIN_TOKEN }}"
        MQTT_USERNAME: "{{ .MOSQUITTO_USERNAME }}"
        MQTT_PASSWORD: "{{ .MOSQUITTO_PASSWORD }}"
  dataFrom:
    - extract:
        key: influxdb
    - extract:
        key: mosquitto
