[agent]
  interval = "30s"
  flush_interval = "10s"
  hostname = "telegraf-vitals"

[[outputs.influxdb_v2]]
  urls = ["http://influxdb-app.vitals.svc.cluster.local:8086"]
  token = "${INFLUX_TOKEN}"
  organization = "vitals"
  bucket = "health"

[[outputs.health]]
  service_address = "http://:8080"

[[inputs.mqtt_consumer]]
  servers = ["tcp://mosquitto-app.database.svc.cluster.local:1883"]
  username = "${MQTT_USERNAME}"
  password = "${MQTT_PASSWORD}"
  topics = ["smartbed/#", "health/#"]
  data_format = "json"

[[inputs.http_listener_v2]]
  service_address = ":8081"
  paths = ["/telegraf"]
  data_format = "json"
