---
apiVersion: v1
kind: ConfigMap
metadata:
  name: unifi-ca-cert
  namespace: network
data:
  ca.crt: |
    -----BEGIN CERTIFICATE-----
    MIIDNTCCAh2gAwIBAgIJQQe2EmsNwJY7MA0GCSqGSIb3DQEBCwUAMBYxFDASBgNV
    BAMTC3VuaWZpLmxvY2FsMB4XDTI2MDMxMjExMDAwMFoXDTI4MDYxNDEyMDAwMFow
    FjEUMBIGA1UEAxMLdW5pZmkubG9jYWwwggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAw
    ggEKAoIBAQD2xP+IZTLiwkLNfqFNFbrbLzRB/XBiJfLPXuwkLAgAD2IrpwTYA9eL
    I7t0QhbVj0Hy4MWBtQFH9caH0mAOPEk51VpHLbTlY4q5rIU5vW0UgaDHsgyhtop2
    iRMohV/1WKkUAzlWoap8/Gpcx4QEfNoZ5rUGnF3r4c3cucWvMLlp/SHrMk7Ap4Cf
    n2coh+sy9ztimv2c4rfO/8T6yeBw57utfkFsf+RhmP0B2noWTQCRwLZUhwV2oKi9
    /xk5XAI9A0w2DLsatpA3Fzs467LhpGyiRucId504ExQMrJXXDh6ZgpvwmEu23QPK
    VMXvP2mxRXAAtpxTuB67p6dtIJaGwzBRAgMBAAGjgYUwgYIwCwYDVR0PBAQDAgL0
    MDEGA1UdJQQqMCgGCCsGAQUFBwMBBggrBgEFBQcDAgYIKwYBBQUHAwMGCCsGAQUF
    BwMIMEAGA1UdEQQ5MDeCC3VuaWZpLmxvY2Fsgglsb2NhbGhvc3SCBVs6OjFdhwR/
    AAABhxD+gAAAAAAAAAAAAAAAAAABMA0GCSqGSIb3DQEBCwUAA4IBAQCiQNV+FGN8
    4t1nqTSj0m2Ujo7Gg5hgQhTg5h+46lMrcjyNP8KlOx+FAYGLXCvKDKfgn024fdom
    tCUjI298yLZon5jKrIwJ1HjxyyvW9x2fepFsMbXZQNrD4UDzl2GpmNH539bboFLA
    V0hXh3x6gzhPvzRdyO5zE0KHgnSFn/6uyFCWNdKOIkpxt0+owPtQ7r6cBgnfvcEA
    M/YpiS3MxwAHVjUN3Q+a2tGGIK8xWzfHz+e0h/sOLxZzoRaEUfApblLmuGGv8+mV
    K5BxNWor16wtisMnt+y+j3JTdteHp4Bxf/CG1olxqXtGFJkASjl1gLN1XhIBW/Uk
    pRQJdFv2q3gK
    -----END CERTIFICATE-----
