---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: envoy-gateway
spec:
  secretName: "envoy-gateway-${SECRET_DOMAIN/./-}-tls"
  secretTemplate:
    labels:
      app.kubernetes.io/name: envoy-gateway-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "${SECRET_DOMAIN}"
  dnsNames:
    - "${SECRET_DOMAIN}"
    - "*.${SECRET_DOMAIN}"
