---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./stanza.yaml
  - ./pluginconfig.yaml
  - ./postgres18-cluster.yaml
  - ./mempalace-db.yaml
  - ./affine-db.yaml
  - ./pooler.yaml
  - ./scheduledbackup.yaml
  - ./scheduledbackup-weekly-full.yaml
  - ./prometheusrule.yaml
  - ./service.yaml
components:
  - ../../../../components/gatus/infrastructure
