apiVersion: v1
kind: Secret
metadata:
    name: rreading-glasses-db
type: Opaque
stringData:
    #ENC[AES256_GCM,data:v26nYbq08mkyLoOJO+WSiUaWhD8CLowkIK5OMWHdPjjOEGxhEC9+UPlGgDLi/+LoP6SoUW+7z52psUhadg8h5uNNc0zJ3BGD2w==,iv:GkceH41s125nh9yqB1cMwiqlRlfCIrZkUsSb7IADanI=,tag:oujpeuFn0XbGukJq3fRhpA==,type:comment]
    #ENC[AES256_GCM,data:/EEhbFuhqH7wVJMsDA+gtqr6zl2w5fXDN1JyGPAYXzCyfSHK/HwtcIyI8/sZhebP7vkzFqqBrcNvM/tRY+G5HpxcBig/V58z,iv:E6KLLOuqswCA2wF+LquhWBG8623Wqa+aORlZYOk4S+k=,tag:/cEnf8XcbUSUjjtz7DM/Cg==,type:comment]
    INIT_POSTGRES_PASS: ENC[AES256_GCM,data:o1BolsBYttQF1yRXrsTDUJBhEZmc3Cp2M2KPUcNlaIw=,iv:X8m/m91m5vMcBR4g2v+kP9img4Sq4OhWcagmvvfMjok=,tag:eVCUHyYObTHxRodyVU44kg==,type:str]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:XsID5yt/XFlmKZaTP3lbFFau/MSgbl2zjvi1Nh4iA8w=,iv:VUwI8XFCEp7ImNaKo7mXmBSVsWf9RR5dDZUi8rBG30Y=,tag:eAWjGKFAPDbnAKNkgF03yQ==,type:str]
sops:
    age:
        - recipient: age1s3dkl4qn66zsj38zl4nkjdw8c6j4d9v8ddd9vwajcfjrz04s2fgsgg3lxy
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBsZWx1WE81WHZ1ZVR1NHVo
            WCtubDVpYlVyeU5WRC8yNEdjeXcrMXI5WlNVClB5bDhBSWhueTJoY05aZ0tlV28w
            NHJ5M0sxbHFQSHhUaFh3dkRLN1UreTQKLS0tIFZWVno0ZkgyTEUxZWFrMkNDeFo5
            eTlSclNMcHNiKzNZTC9RcWMwY0YySGsKaKvo60ErWto8K+arEUaucU6TsLwFfToo
            GYqIi/NNPlTcXSzbF4YrwEJH+IiaGEh/M4K/I85w12Q7B6eT5vhByg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-06-07T04:21:14Z"
    mac: ENC[AES256_GCM,data:gkwJlJrARzL5jHslhKKmP2kAd6uDE4tcYHSA71ZxzGal8LCXwHmz7VfhQ+E8VZGKaK4uqGc4w9HmlkgBCnhirflE8PtnuYn6ygPD8BBxVrTQyBDNhOaXfBxHLqmq+Lj4qBpTL7uH/LQg7nfSqmY3xLD4S9mp5c6h55Iq/N9tG0A=,iv:BshfLFqNiIjceehrGEloyd8XJTL97Dug7X+DOMrn2E0=,tag:o8v2LGtH1g8iW7a+mq1kkw==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.11.0
