---
# yaml-language-server: $schema=https://json.schemastore.org/kustomization
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cortex

components:
  - ../../components/common

resources:
  # Applications
  - ./mempalace/ks.yaml
  - ./mempalace-bridge/ks.yaml
  - ./lighthouse/ks.yaml
