---
# yaml-language-server: $schema=https://k8s-schemas.home-operations.com/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: komf
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: komf-secret
    template:
      engineVersion: v2
      data:
        KOMF_KAVITA_API_KEY: "{{ .KOMF_KAVITA_API_KEY }}"
        KOMF_MAL_CLIENT_ID: "{{ .KOMF_MAL_CLIENT_ID }}"
        KOMF_COMICVINE_API_KEY: "{{ .KOMF_COMICVINE_API_KEY }}"
        KOMF_BANGUMI_TOKEN: "{{ .KOMF_BANGUMI_TOKEN }}"
  dataFrom:
    - extract:
        key: komf
