---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: hume-influx
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: hume-influx-secret
    template:
      engineVersion: v2
      data:
        config.toml: |
          [[users]]
          name = "Gavin"
          email = "{{ .HUME_EMAIL }}"
          password = "{{ .HUME_PASSWORD }}"

          [influx]
          url = "http://influxdb.vitals.svc.cluster.local:8086"
          bucket = "health"
          token = "{{ .INFLUXDB_ADMIN_TOKEN }}"
          org = "vitals"

          [main]
          log_level = "INFO"
          loop_minutes = 60
  dataFrom:
    - extract:
        key: hume-influx
    - extract:
        key: influxdb
