---
# yaml-language-server: $schema=https://kubernetes-schemas.nerdz.cloud/external-secrets.io/externalsecret_v1.json
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: qdrant
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword-connect
  target:
    name: qdrant-secret
    template:
      engineVersion: v2
      data:
        QDRANT__SERVICE__API_KEY: "{{ .QDRANT_API_KEY }}"
        QDRANT__SERVICE__READ_ONLY_API_KEY: "{{ .QDRANT_METRICS_API_KEY }}"
  dataFrom:
    - extract:
        key: qdrant
