---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "devcontainer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".devcontainer/ci/**"]
  pull_request:
    branches: ["main"]
    paths: [".devcontainer/ci/**"]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  devcontainer:
    if: ${{ github.repository == 'onedr0p/cluster-template' }}
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@ce360397dd3f832beb865e1373c09c0e9f86d70a # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@4d04d5d9486b7bd6fa91e7baf45bbb4f8b9deedd # v4
        with:
          platforms: linux/amd64 #,linux/arm64

      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@4907a6ddec9925e35a0a9e82d7399ccc52663121 # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: devcontainers/ci@b63b30de439b47a52267f241112c5b453b673db5 # v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          # cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          imageTag: base,latest
          platform: linux/amd64 #,linux/arm64
          configFile: .devcontainer/ci/devcontainer.json
          push: ${{ github.event_name == 'pull_request' && 'never' || 'always' }}
