---
# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json
name: "devcontainer"

on:
  workflow_dispatch:
  push:
    branches: ["main"]
    paths: [".devcontainer/ci/**"]
  pull_request:
    branches: ["main"]
    paths: [".devcontainer/ci/**"]
  schedule:
    - cron: "0 0 * * *"

concurrency:
  group: ${{ github.workflow }}-${{ github.event.number || github.ref }}
  cancel-in-progress: true

jobs:
  devcontainer:
    if: ${{ github.repository == 'onedr0p/cluster-template' }}
    name: publish
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up QEMU
        uses: docker/setup-qemu-action@06116385d9baf250c9f4dcb4858b16962ea869c3 # v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@d7f5e7f509e45cec5c76c4d5afdd7de93d0b3df5 # v4
        with:
          platforms: linux/amd64 #,linux/arm64

      - if: ${{ github.event_name != 'pull_request' }}
        name: Login to GitHub Container Registry
        uses: docker/login-action@650006c6eb7dba73a995cc03b0b2d7f5ca915bee # v4
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: devcontainers/ci@513af61f4de4f75d37e4438f184ba4358f0fc1ca # v0.3
        env:
          BUILDX_NO_DEFAULT_ATTESTATIONS: true
        with:
          imageName: ghcr.io/${{ github.repository }}/devcontainer
          # cacheFrom: ghcr.io/${{ github.repository }}/devcontainer
          imageTag: base,latest
          platform: linux/amd64 #,linux/arm64
          configFile: .devcontainer/ci/devcontainer.json
          push: ${{ github.event_name == 'pull_request' && 'never' || 'always' }}
